Book add form
akai-org/AKAI-bookcrossing pull request #20
Opened 2020-10-26 19:27 UTC by piter104

2020-10-26 22:14 UTC, Szczepaniak-M requested changes

2020-10-26 22:14 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/list/ListBookRestController.java
> +    @GetMapping("/form")
To jest dodawanie książki, więc URL powinien być /book/add

2020-10-26 22:14 UTC, Szczepaniak-M commented on src/main/resources/templates/form.html
> +    <p>Opis: <input type="text" th:field="*{description}"/></p>
Zmienić opis z  input type="text"  na textarea

2020-10-26 22:14 UTC, Szczepaniak-M commented on src/main/resources/templates/form.html
> +<form action="#" th:action="@{/form}" th:object="${book}" method="post">
Zmienić link na nowy

2020-10-26 22:14 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/list/ListBookRestController.java
> +    @PostMapping("/form")
Również do zmiany

2020-10-26 22:14 UTC, Szczepaniak-M commented on src/main/resources/templates/form.html
> +    <p>Opis: <input type="text" th:field="*{description}"/></p>
Wszystkie 3 pola obecnie mogą być puste. Dodać walidacje czy takie nie są

2020-10-26 22:14 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/list/ListBookRestController.java
> +        bookDao.insertBook(book);
Dodawanie wydzielić do osobnego komponentu, który będzie jeszcze dodawał informację o właścicielu do książki i dopieor wtedy insertował do bazy. Właścicielem ma być osoba obecnie zalogowana.

2020-10-28 08:02 UTC, piter104 commented on src/main/resources/templates/formResult.html
> +    </style>
Nie działało mi dołączenie pliku css, więc na ten moment zostawiłem cssa w środku

2020-10-28 10:02 UTC, Szczepaniak-M approved these changes

2020-10-28 10:02 UTC, merged