Rest controller added
akai-org/AKAI-bookcrossing pull request #30
Opened 2020-12-04 21:25 UTC by piter104

2020-12-05 22:52 UTC, Szczepaniak-M requested changes

2020-12-05 22:52 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/list/BookRestController.java
> +public class BookRestController {
Brakuje endpointa do samego ustawiania atrybutu isAvailable.

2020-12-05 22:52 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/list/BookBean.java
> +    BookRentRequest getBookRentRequestByOwnerAndBookIds(BookRentRequest bookRentRequest) {
Nieoptymalne - więcej opisane przy Mapperze

2020-12-05 22:52 UTC, Szczepaniak-M commented on src/main/resources/mybatis/BookDaoMapper.xml
> +        SELECT tbur.*
Funkcja ma na celu tylko sprawdzenie czy taki obiekt już jest czy nie. Nie ma sensu wyciagać całego obiektu baseBookRentRequestMap, z którego wyciagnieciem wiąże sie wykonanie kolejnych zapytań. Niech zapytanie zwraca wynik count(*) i potem operuj na integerze.  Ograniczamy w en sposób ilość zapytan SQL, a więc i czas wykonnia całości i blokowania zasobów.  Pamietaj by wyrzucić wtedy JOINy, bo nie sa potrzebne - kolejna optymalizacja

2020-12-06 00:00 UTC, piter104 commented on src/main/java/pl/akai/bookcrossing/list/BookRestController.java
> +    }
Nie wiem czy dobrze zrozumiałem tą uwagę odnośnie ustawiania IsAvailable, ale jeżeli miałaby się wywoływać na "zakończenie wypożyczenia" to mógłbym jeszcze dodać usunięcie aktualnego czytelnika

2020-12-06 00:04 UTC, piter104 commented on src/main/java/pl/akai/bookcrossing/list/BookBean.java
> +    Integer getBookRentRequestByOwnerAndBookIds(BookRentRequest bookRentRequest) {
Szczerze nie miałem pomysłu na inną intuicyjną nazwę

2020-12-06 12:36 UTC, Szczepaniak-M approved these changes

2020-12-06 12:36 UTC, merged