New REST endpoints - Spring course
akai-org/AKAI-bookcrossing pull request #64
Opened 2022-02-27 21:23 UTC by sniochup

2022-02-27 21:44 UTC, Szczepaniak-M requested changes

2022-02-27 21:44 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/book/BookRestController.java
> +    @GetMapping("/books/list")
```suggestion
    @GetMapping("/api/books")
```

2022-02-27 21:44 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/book/BookRestController.java
> +    @GetMapping("/book/details/{id}")
```suggestion
    @GetMapping("/api/books/{id}")
```

2022-02-27 21:44 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/book/BookRestController.java
> +    public Dictionary<String, Object> bookDetails(@PathVariable(name = "id") Integer id) {
Do poprawy - zamiast Dictionary Map: https://docs.oracle.com/javase/7/docs/api/java/util/Dictionary.html

2022-02-27 21:50 UTC, Szczepaniak-M requested changes

2022-02-27 21:50 UTC, Szczepaniak-M commented on src/main/java/pl/akai/bookcrossing/book/BookRestController.java
> +        dict.put("bookDetails", bookBean.getBookById(id));
```suggestion
        dict.put("book", bookBean.getBookById(id));
```

2022-02-27 22:21 UTC, sniochup commented on src/main/java/pl/akai/bookcrossing/book/BookRestController.java
> +    public Dictionary<String, Object> bookDetails(@PathVariable(name = "id") Integer id) {
Poprawiono: https://github.com/akai-org/AKAI-bookcrossing/commit/e9937d04d4832dcececfbcfa79d6deca65b32f84

2022-02-28 08:13 UTC, Szczepaniak-M approved these changes

2022-02-28 08:14 UTC, merged